### PR TITLE
New: Adding anypoint version of paper-* elements

### PR DESCRIPTION
**Pull request by jarrodek**
- contains paper-input, paper-checkbox, form behaviors
- is to replace `anypoint` branches of arc core elements to maintain single code base
- **potentially breaking changes in styling** since it removes `--anypoint-` mixins and variables

### CODE REVIEW

**Comment by nescalante** [comment]
LGTM, can you please resolve conflicts?

**Comment by mcampo** [comment]
I don't follow, is the anypoint styling now moved into the main repo?

**Comment by jarrodek** [comment]
Yes, it shouldn't be done like we did it before. It's not scalable. Uri discouraged me from continuing `anypoint` branches and I agree. 
Own created paper elements as a replacement for the API console allows us to replace all paper UI controls with anypoint's without styling another elements because it's happening all at once.

**Comment by mcampo** [comment]
Awesome, we should pay extra attention to styling immediately after we merge this to make sure any styling we have made is not lost.
One more question, is there a reason why the `raml-path-selector` component is still pointin to the `anypoint` branch?

**Comment by jarrodek** [comment]
Yes, I've ask Nazar is there's anything else than icons to consider. He made few more customizations to the code. So give me time until Wednesday to investigate if we can use master branch or if we need to merge changes made i anypoint to master (which will be more complex).

Also, icons may be restored to ARC's icons. If so, I'll prepare a replacement element for that in about an hour so no changes in the code base will be necessary.

**Comment by jarrodek** [comment]
I've resolved conflicts in bower file and it's in my fork but for some reason it doesn't update it here. Any idea why?

**Comment by nescalante** [comment]
is it fine now? otherwise I can revert my commit

**Comment by jarrodek** [comment]
I think it's working

**Pull request merged**
